// export const metadata = {
// 	title: "Next.js",
// 	description: "Generated by Next.js",
// };

// export default function RootLayout({ children }) {
// 	return (
// 		<html lang="en">
// 			<body>{children}</body>
// 		</html>
// 	);
// }

// ==============================================

// import Navigation from "./_components/Navigation";

import { ReservationProvider } from "./_components/ReservationContext";
import { Josefin_Sans } from "next/font/google";

const josefin = Josefin_Sans({
	subsets: ["latin"],
	display: "swap",
});

// console.log(josefin);

import Header from "./_components/Header";

import "@/app/_styles/globals.css";

export const metadata = {
	// title: "The Wild Oasis",

	title: {
		template: "%s - The Wild Oasis",
		default: "Welcome: The Wild Oasis",
	},

	description:
		"Luxurious cabin hotel, located in the heart of the Italian Dolomites, surrounded by beautiful mountains and dark forests",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body
				className={`${josefin.className} antialiased bg-primary-950 text-primary-100 min-h-screen flex flex-col relative`}
			>
				{/* <header>
					<Logo />

					<Navigation />
				</header> */}

				<Header />

				<div className="flex-1 px-8 py-12 grid">
					<main className="max-w-7xl mx-auto w-full">
						{/* client component  */}
						<ReservationProvider>
							{children} {/* server compont  */}
						</ReservationProvider>
					</main>
				</div>

				{/* <footer>Copyright by The Wild Oasis</footer> */}
			</body>
		</html>
	);
}
